### PR TITLE
Made it work with a starter account

### PR DESCRIPTION
**Pull request by tgsoverly**
I went ahead and updated the zen push to work with a new "account_type" option

### CODE REVIEW

**Comment by tgsoverly** [comment]
I have been working on my master the last couple days.  I have some extra features, that are all on this pull request.  I can break it up if you wish.
1.  Added some tests for finding the category/forum/topic
2.  Enabled support for starter accounts
3.  Automatically attach files in an "attachments" folder to the topic.
4.  Allow for the nesting of files inside folders with the same name.

**Comment by afilbert** [comment]
Well, looks like they eol'd API v1. Gonna need some more work to keep this alive. :(

**Comment by nfo** [comment]
I, maintainer of the project, don't use Zendesk anymore. So I'm ok giving github/rubygems rights. Anyone interested ?

**Comment by tgsoverly** [comment]
I would be interested.

**Comment by tgsoverly** [comment]
I am closing this, because it has been some time with no activity.

**Pull request closed without merging**
